React capstone project - Metrics webapp
HossainAraf/metrics-webapp pull request #1
Opened 2023-11-16 21:33 UTC by HossainAraf

***Methods implemented:***

-  Chosse an API should allow us to get numeric values based on a parameter;
- Interactions:

**Home page**

When the page loads, the webapp shows a bunch of countries with their corresponding population.

When the user clicks (or taps) on a category item (A Country), the application navigates to the details page.

**Details page**

In the details page, the webapp retrieves data from the API to show detailed data (Currency, capital etc.) in the category.
-When the user clicks on the "Back" button (<), the user navigates to the home page.

Testing requirements

- Create unit tests for pure functions in Redux code.
- Create integration tests for the application using the React Testing Library.

- The project is a single-page application (SPA) built with React and Redux.
- The data retrieved from the API should be stored in the Redux store.
- We should filter the data that we retrieve from the API using a Filter stateless component;
- Every page (the main page and the pages for each item) should have a unique route within the SPA.
- The project should be deployed and accessible online using [Render](https://render.com/), [Netlify](https://www.netlify.com/) or [GitHub Pages](https://pages.github.com/).
- Add a link to the online version of your app to your README file.

2023-11-16 23:07 UTC, Felix45 requested changes
Hi @HossainAraf, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good styling and beautiful UI design :white_check_mark: 
- [x] Countries listing and details pages work as expected :white_check_mark: 
- [x] Application uses `Redux` for state management :white_check_mark:  
- [x] Git flow is used correctly :white_check_mark:   
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 23:07 UTC, Felix45 commented on README.md
> +- [Video description]()
- [ Required ] I think it would be great if you add the link to the video presentation on your readme file, currently, this link redirects to the root of your repository and not to the project's video presentation as requested in the project requirements. Please update this with a valid video URL. The video should cover the following points as listed in the project requirements.

## Project requirements
![Screenshot from 2023-11-17 01-53-11](https://github.com/HossainAraf/metrics-webapp/assets/16392046/b01b6594-c078-4d27-ba2c-a977e84990b7)

2023-11-16 23:07 UTC, Felix45 commented on src/components/Home.jsx
> +      <Row className="center">STATS BY COUNTRY</Row>
- [ Required ] I think it would be nice if you made it possible to `filter` the countries on your homepage using a `Filter stateless component` as stated in the project requirements. This means that you could provide a component with an `input` field that makes it possible for a user to search for a country by typing a search parameter, then the list of countries would be updated according to the search parameter the user enters. 

This is just a suggestion so feel free to implement a different solution if you find one.

## Project requirements
![Screenshot from 2023-11-17 01-48-43](https://github.com/HossainAraf/metrics-webapp/assets/16392046/17b91f84-843b-4962-9b4f-94eed9f6ef33)

2023-11-17 17:34 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️
Hi @HossainAraf , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![congrats](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e47lmmwe9du16odvy6ah74j173xbp6sso5dj40lkppm&ep=v1_gifs_search&rid=200w.webp&ct=g)

 ## Highlights
:heavy_check_mark: Linters passing
:heavy_check_mark: Correct GitFlow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 17:34 UTC, zeff96 commented on src/components/CountryFilter.jsx
> +  const filteredCountries = countries.filter((country) => country.region === 'Asia');
- [ ] Hello, as mentioned by the previous reviewer and a requirement in the project guideline,To enhance user experience, let's incorporate a search field on the homepage, allowing users to filter the displayed list of countries based on their input. Simply add a search input and implement state management for smooth list filtering. This addition ensures users can easily explore and find specific countries, enhancing the overall usability of the platform. 🕵️‍♂️🔍 Happy coding! 💻🚀

![Screenshot from 2023-11-17 20-24-54](https://github.com/HossainAraf/metrics-webapp/assets/112261237/6e3f6c78-135d-4d8a-b938-c269edff9003)

2023-11-17 19:24 UTC, zeff96 approved these changes
### Status: APPROVED :green_circle: 
Hi @HossainAraf, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media0.giphy.com/media/wYpiTsv2OCUs17cNl1/200w.webp?cid=ecf05e471xz8kat1e64s4j8xgnjph7uu4jgtsqs1wn4aprzx&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Linters passing
:heavy_check_mark: Descriptive pull request

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 19:33 UTC, merged